### ISSUE TITLE
Can't upload .mp3 files.

### ISSUE THREAD

**Issue by lavanoid** [mtheall/ftbrony#16]
Tried uploading a .mp3 using FileZilla Client for Windows, but it keeps saying "Replace file" - do idea why this happens...

Doesn't work with ES File Explorer for Android or XBMC, either.

Thanks for the Homebrew!

**Comment by mtheall** [comment]
There's nothing inherent about mp3 files that would cause it to fail to upload. My guess is that you might be trying to upload a file that has non-ASCII characters. The 3DS only supports ASCII and UCS-2 for names on the SD card, and I haven't looked into UCS-2 support, especially since that could include having to translate from other locales (if anything I would probably only support UCS-2 directly or translating from UTF-8).

**Comment by lavanoid** [comment]
Here's the most amount of log information/evidence that I could possibly provide: https://www.dropbox.com/sh/f9d53e8by535x1z/AAB4lBEr4rGIMZ7mQcRHLF36a?dl=0  (The directory contains all the files needed)

**Comment by mtheall** [comment]
Okay I see. FileZilla is trying to append to the file, which I have not implemented yet. Does it partially transfer and then this happens? If the file already exists, then of course you're going to get that dialog about replacing the file. What happens if you choose overwrite?

**Comment by lavanoid** [comment]
It partially transfers, then the dialogue pops up again. When I press "overwrite", it tries to copy again and the same dialogue appears again.

**Comment by mtheall** [comment]
Can you show me a larger part of the FileZilla log? It would be good if you could just paste the entire text.

**Comment by lavanoid** [comment]
Ok. Hang on - I'll take about 10 minutes, as I'm using the SD at the moment...

**Comment by lavanoid** [comment]
Here you go:

Status:	Connecting to 192.168.0.8:5000...
Status:	Connection established, waiting for welcome message...
Response:	200 Hello!
Command:	USER anonymous
Response:	230 OK
Command:	SYST
Response:	215 UNIX Type: L8
Command:	FEAT
Response:	211 
Status:	Server does not support non-ASCII characters.
Status:	Connected
Status:	Retrieving directory listing...
Command:	PWD
Response:	257 "/"
Command:	TYPE I
Response:	200 OK
Command:	PASV
Response:	227 192,168,0,8,19,138
Command:	LIST
Response:	150 Ready
Response:	226 OK
Status:	Directory listing successful
Status:	Retrieving directory listing...
Command:	CWD Music
Response:	200 OK
Command:	PWD
Response:	257 "/Music"
Command:	PASV
Response:	227 192,168,0,8,19,139
Command:	LIST
Response:	150 Ready
Response:	226 OK
Status:	Directory listing successful
Status:	Connecting to 192.168.0.8:5000...
Status:	Connection established, waiting for welcome message...
Response:	200 Hello!
Command:	USER anonymous
Response:	230 OK
Status:	Server does not support non-ASCII characters.
Status:	Connected
Status:	Starting upload of C:\Users\Lavanoid\Music\Blood On The Dance Floor\Bad Blood (Deluxe Edition)\01 - Unchained.mp3
Command:	CWD /Music
Response:	200 OK
Command:	PWD
Response:	257 "/Music"
Command:	TYPE I
Response:	200 OK
Command:	PASV
Response:	227 192,168,0,8,19,140
Command:	STOR 01 - Unchained.mp3
Response:	150 Ready
Response:	426 Connection broken during transfer
Error:	File transfer failed after transferring 262,144 bytes in 1 second
Status:	Starting upload of C:\Users\Lavanoid\Music\Blood On The Dance Floor\Bad Blood (Deluxe Edition)\01 - Unchained.mp3
Status:	Retrieving directory listing...
Command:	PASV
Response:	227 192,168,0,8,19,141
Command:	LIST
Response:	150 Ready
Response:	226 OK
Command:	PASV
Response:	227 192,168,0,8,19,142
Command:	APPE 01 - Unchained.mp3
Error:	Could not write to transfer socket: ECONNRESET - Connection reset by peer
Response:	502 unavailable
Error:	File transfer failed after transferring 262,144 bytes in 1 second
Status:	Starting upload of C:\Users\Lavanoid\Music\Blood On The Dance Floor\Bad Blood (Deluxe Edition)\01 - Unchained.mp3
Status:	Retrieving directory listing...
Command:	PASV
Response:	227 192,168,0,8,19,143
Command:	LIST
Response:	150 Ready
Response:	226 OK
Command:	PASV
Response:	227 192,168,0,8,19,144
Command:	APPE 01 - Unchained.mp3
Error:	Could not write to transfer socket: ECONNRESET - Connection reset by peer
Response:	502 unavailable
Error:	File transfer failed after transferring 262,144 bytes in 1 second
Status:	Starting upload of C:\Users\Lavanoid\Music\Blood On The Dance Floor\Bad Blood (Deluxe Edition)\01 - Unchained.mp3
Status:	Retrieving directory listing...
Command:	PASV
Response:	227 192,168,0,8,19,145
Command:	LIST
Response:	150 Ready
Response:	226 OK
Command:	PASV
Response:	227 192,168,0,8,19,146
Command:	APPE 01 - Unchained.mp3
Response:	502 unavailable
Error:	Critical file transfer error after transferring 262,144 bytes in 1 second
Status:	Starting upload of C:\Users\Lavanoid\Music\Blood On The Dance Floor\Bad Blood (Deluxe Edition)\01 - Unchained.mp3
Command:	PASV
Response:	227 192,168,0,8,19,147
Command:	APPE 01 - Unchained.mp3
Error:	Could not write to transfer socket: ECONNRESET - Connection reset by peer
Response:	502 unavailable
Error:	File transfer failed after transferring 262,144 bytes in 1 second
Status:	Starting upload of C:\Users\Lavanoid\Music\Blood On The Dance Floor\Bad Blood (Deluxe Edition)\01 - Unchained.mp3
Status:	Retrieving directory listing...
Command:	PASV
Response:	227 192,168,0,8,19,148
Command:	LIST
Response:	150 Ready
Response:	226 OK
Command:	PASV
Response:	227 192,168,0,8,19,149
Command:	STOR 01 - Unchained.mp3
Response:	150 Ready
Response:	426 Connection broken during transfer
Error:	File transfer failed after transferring 262,144 bytes in 1 second
Status:	Starting upload of C:\Users\Lavanoid\Music\Blood On The Dance Floor\Bad Blood (Deluxe Edition)\01 - Unchained.mp3
Status:	Retrieving directory listing...
Command:	PASV
Response:	227 192,168,0,8,19,150
Command:	LIST
Response:	150 Ready
Response:	226 OK
Command:	PASV
Response:	227 192,168,0,8,19,151
Command:	APPE 01 - Unchained.mp3
Error:	Could not write to transfer socket: ECONNRESET - Connection reset by peer
Response:	502 unavailable
Error:	File transfer failed after transferring 262,144 bytes in 1 second
Status:	Starting upload of C:\Users\Lavanoid\Music\Blood On The Dance Floor\Bad Blood (Deluxe Edition)\01 - Unchained.mp3
Status:	Retrieving directory listing...
Command:	PASV
Response:	227 192,168,0,8,19,152
Command:	LIST
Response:	150 Ready
Response:	226 OK
Status:	Skipping upload of C:\Users\Lavanoid\Music\Blood On The Dance Floor\Bad Blood (Deluxe Edition)\01 - Unchained.mp3
Status:	File transfer successful, transferred 163 bytes in 2 seconds

**Comment by lavanoid** [comment]
After clicking "overwrite" once, I cancelled it the second time, but FileZilla says it was "successful".

**Comment by mtheall** [comment]
Okay it looks like for some reason we failed to receive data mid-transfer and so we disconnected. It would be good if we could see the error message on the 3DS before it flew by. It would say "recv: <some number> <some string>"

**Comment by lavanoid** [comment]
I see. Do you mind having everything as a video, or should I screenshot the 3DS?

**Comment by mtheall** [comment]
Maybe I can just give you a special build that logs to SD card.

**Comment by lavanoid** [comment]
Yeah, that will be perfect! I'll wait until your ready then...

**Comment by mtheall** [comment]
http://mtheall.com/~mtheall/ftbrony_logging.3dsx

Run that with your problem and then upload the ftbrony.log file to dropbox or something.

**Comment by lavanoid** [comment]
It seems to not be working at all. FileZilla just sticks on: 

Status:	Connecting to 192.168.0.8:5000...
Status:	Connection established, waiting for welcome message...
Error:	Could not connect to server
Status:	Waiting to retry...
Status:	Delaying connection for 1 second due to previously failed connection attempt...
Status:	Connecting to 192.168.0.8:5000...
Status:	Connection attempt failed with "ECONNREFUSED - Connection refused by server".
Error:	Could not connect to server


The log is here: https://www.dropbox.com/s/e665x26drskgpez/ftbrony.log?dl=0
and here's an image: https://www.dropbox.com/s/ujjfpw63loxa8l5/DSC_0523.jpg?dl=0

**Comment by mtheall** [comment]
Okay sorry I gave you a build which had some experimental socket stuff I was working on. I replaced the ftbrony_logging.3dsx with a new one, so try that.

**Comment by mtheall** [comment]
I tried an upload using your file and it transferred all in one go. No issue on my end :(

**Comment by lavanoid** [comment]
Hugh, just tried the newer version of the logging ftbrony and it seems to work now. Strange. Perhaps I was using an older version of ftBrony before? I noticed the UI on the latest ftBrony is a lot different to that of the one I was using.

**Comment by mtheall** [comment]
I haven't committed the new UI yet but otherwise the ftp code itself hasn't changed from what's on github. Are you sure you were using the latest version before?

**Comment by lavanoid** [comment]
I was using version 1.0, before.

**Comment by mtheall** [comment]
Yeah I mean did you pull the latest code from github and the latest libctru code before building?

**Comment by mtheall** [comment]
The version number hasn't changed from 1.0, but I'm probably doing a 1.1 release in the near future.

**Comment by lavanoid** [comment]
HHmm. Strange. Well, FileZilla seems to like it now anyway.

I would compile releases by myself and I have DevKitArm which was installed with DevKitPro, but it doesn't let me build 3ds homebrew - I always get errors when running "make" from cmd. I'm using Windows btw. 

I followed the guide on 3dbrew but it only states where to get the DevKitArm installer from, the rest is Linux oriented (as Windows is configured by the installer).

**Comment by mtheall** [comment]
Specifically https://github.com/mtheall/ftbrony/commit/de309c37dab82dd236de64595dd9004c1ed64265 should have fixed partial transfers.

**Comment by lavanoid** [comment]
This is the ftBrony I was using previously,:https://www.dropbox.com/sh/q839p1s30gxoc15/AAB1y2UAxt52I7cPilR6tLeLa?dl=0 . Perhaps you could attempt to replicate the bug with this version, to see if it was just this build that was buggy?
