### ISSUE TITLE
What is the point of all those "ifndef _3DS" if the objective platform is 3DS only?

### ISSUE THREAD

**Issue by PerikiyoXD** [mtheall/ftbrony#21]
I dont really know if this is because is scripter behavior to define the platforms, but i dont really know why youre doing this.

**Comment by fincs** [comment]
ftbrony can also be compiled and run on Linux.

**Comment by PerikiyoXD** [comment]
:facepalm:

**Comment by mtheall** [comment]
The Linux compilation is mainly for test purposes. It's a quicker test cycle for minor updates than trying to perform them on the 3DS itself.
