### ISSUE TITLE
STAT support in near future?

### ISSUE THREAD

**Issue by s3r1alpari4h** [mtheall/ftbrony#28]

**Comment by mtheall** [comment]
Added in 920cd96c

**Comment by s3r1alpari4h** [comment]
Yay!

**Comment by mtheall** [comment]
Can you tell me what client you were using that was sending STAT?

**Comment by s3r1alpari4h** [comment]
FX by nextapp. It's a Android file manager that has FTP support. I think it uses stat to get file details like size etc
