### ISSUE TITLE
Show right file modify time for LIST?

### ISSUE THREAD

**Issue by wjchen** [mtheall/ftbrony#29]
It's easy for linux version.
3ds's fstat seems not get st_mtime?

**Comment by mtheall** [comment]
Haven't figured out how to get timestamp with fs:user yet.

**Comment by mtheall** [comment]
I'm gonna try out https://3dbrew.org/wiki/FS:ControlArchive tomorrow to if that's what I need, and how slow it might be.

**Comment by mtheall** [comment]
Implemented with 74ec300f

**Comment by wjchen** [comment]
Great!
